### ISSUE TITLE
Decryption failures in nvim

### ISSUE THREAD

**Issue by djvs** [jamessan/vim-gnupg#116] opened 2020-12-12 06:11 UTC
Steps to reproduce (for me at least):

```
killall gpg-agent # (fresh state)
vim myfile.gpg
-> Message could not be decrypted! (Press ENTER)
gpg -d myfile.gpg
-> (prompts for password, and after entering it, outputs the file)
vim myfile.gpg
-> (opens the file in vim as expected)
```

init.vim only has this re: gnupg:
```
Plug 'jamessan/vim-gnupg'
```

and added these to no effect:
```let g:GPGPreferSymmetric=1
let g:GPGUseAgent=1
```

~/.gnupg/gpg-agent.conf has pinentry-program /usr/bin/pinentry-curses, pinentry-timeout 0, and a more or less default default-cache-ttl and max-cache-ttl.  

Hard to check but this may have coincided with switching from vim to nvim.

**Comment by jamessan** [comment] 2020-12-14 00:06
> Hard to check but this may have coincided with switching from vim to nvim.

Most likely.  Neovim implements interaction with command-line tools differently and I haven't had time to switch to a job-based implementation.

You can either use a non-terminal based pinentry agent or "prime" gpg before running nvim.

Duplicate of #32

**Closed by jamessan** 2020-12-14 00:06 UTC
