### ISSUE TITLE
Vim doesn't ask for the password everytime I open a GPG encrypted file.

### ISSUE THREAD

**Issue by sibinpthomas** [jamessan/vim-gnupg#87] opened 2018-02-09 16:05 UTC
I am using this plugin with the variable `g:GPGPreferSymmetric` set.

I save and close the .gpg file with a password and when I reopen it, it is decrypted automatically without prompting me to enter the password. How do I ensure that the password is asked everytime I open the file?

My setup -
 
 * gVim ver 8.0
 * Windows 10
 * GPG4Win 3.0.3 (which consists of) -
    * GnuPG 2.2.4
    * Kleopatra 3.0.2
    * GPA 0.9.10
    * GpgOL 2.0.6
    * GpgEX 1.0.5

Question posed on SO - https://stackoverflow.com/questions/48709340/how-do-i-make-vim-to-ask-for-the-password-everytime-i-open-a-gpg-encrypted-file

**Comment by jamessan** [comment] 2018-02-09 18:35
Duplicate of #85

**Closed by jamessan** 2018-02-09 18:35 UTC
